### ISSUE TITLE
KeyError: 'getpwnam(): name not found

### ISSUE THREAD

**Issue by benjibenoit** [harapekoaomushi/jupyterhub-wordpressauthenticator#1]
Hello.

I've installed your plugin to connect with Wordpress's account. But when I want to connect I see that in the console :

> [E 2018-06-29 14:13:17.493 JupyterHub web:1621] Uncaught exception GET /hub/user/iapprendre/ (::ffff:127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/hub/user/iapprendre/', version='HTTP/1.1', remote_ip='::ffff:127.0.0.1')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 999, in get
        await self.spawn_single_user(user)
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 670, in spawn_single_user
        await gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future)
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 625, in finish_user_spawn
        await spawn_future
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/user.py", line 486, in spawn
        raise e
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/user.py", line 406, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/spawner.py", line 1076, in start
        env = self.get_env()
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/spawner.py", line 1069, in get_env
        env = self.user_env(env)
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/spawner.py", line 1056, in user_env
        home = pwd.getpwnam(self.user.name).pw_dir
    KeyError: 'getpwnam(): name not found

and in the website I see : 

> 500 : Internal Server Error
Failed to start your server on the last attempt. Please contact admin if the issue persists.
You can try restarting your server from the home page.

How can I fix that ?

Regards,

Shankiflang

**Comment by harapekoaomushi** [comment]
@shankiflang 

Thank you for your comment.

Since I was away from the project for a while, I can not show an appropriate solution.
But as I read at your log, the user (for instance) on your operating system (PAM user) which has the same name as the wordpress user you try to login couldn't be found. The authentication process itself may be working well (There is no relevant part in your log, so I do not know the exact thing).

One possibility is that the spawner of Jupyterhub you are using is not processing such as creating a new user when there is no same name user in the user management system used by the spawner as the user name who got the authentication.

It is not fundamentally a solution but why do not you try using DockerSpawner (and so on) as Spawner?

Thank you,
  Harapeko Aomushi
